files = { glob = ["src/**/*.rs", "traktor-api/**/*.m?[jt]s", "*.toml", "\\.yaml", "traktor-api/**/*.json", "dist/*.xml"] }

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [{ id = "trailing-whitespace" }, { id = "check-case-conflict" }, { id = "end-of-file-fixer" }, { id = "check-toml" }, { id = "check-yaml" }, { id = "check-json" }, { id = "pretty-format-json", args = ["--autofix"] }, { id = "check-xml" }]

[[repos]]
repo = "https://github.com/doublify/pre-commit-rust"
rev = "v1.0"
hooks = [{ id = "fmt" }, { id = "cargo-check" }]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-eslint"
rev ="v9.14.0"
hooks = [{ id = "eslint", args = ["--fix", "--report-unused-disable-directives"], files = "\\.m?[jt]s$", types = ["file"], verbose = true, stages = ["pre-commit", "manual"], additional_dependencies = ["eslint@^9.14.0", "@eslint/js", "typescript-eslint", "eslint-plugin-jsdoc@^v50.4.3", "eslint-plugin-diff@^2.0.3"] }]
