# Generated by rust2rpm 27
%bcond check 1

%global crate danceinterpreter-rs

Name:           rust-danceinterpreter-rs
Version:        0.6.5
Release:        %autorelease
Summary:        Danceinterpreter in Rust

License:        GPL-3.0-or-later
URL:            https://crates.io/crates/danceinterpreter-rs
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Danceinterpreter in Rust.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README.md
%doc statics.txt
%{_bindir}/danceinterpreter-rs

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
