name: CI
on:
  push:
    branches: [ "iced-gui" ]

  pull_request:
    branches: [ "main", "iced-gui" ]

permissions:
  contents: read

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  check_and_test:
    uses: ./.github/workflows/check-and-test.yml
    needs: pre-commit