name: Publish Flatpak

on:
  release:
    types: [published]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/klassenserver7b/fp-gh-actions-rust:fd-24.08
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Generate Cargo.lock
        run:  cargo generate-lockfile

      - name: Generate cargo-sources.json
        run:  flatpak-cargo-generator Cargo.lock -o build-aux/cargo-sources.json

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: danceinterpreter.flatpak
          manifest-path: build-aux/de.klassenserver7b.danceinterpreter-rs.json
          cache-key: flatpak-builder-${{ github.sha }}


